function addIsoDeviceGuiBindings(app,binding_logger)
%% ROBOT GRIPPER TAB
            iso_bm = Binding.BindingManager('IsoDevice',binding_logger);
            app.binding_managers.gripper = iso_bm;
%             app.RoboterGreiferTab.binding_managers = [app.RoboterGreiferTab.binding_managers, robot_gripper_bm];
%             robot_gripper_bm.timer_target_period = 0.1;

            iso_bm.addBinding(... %Winkel Zange Links
                Binding.PropertyBinding(...
                app.process.isoDevice.robot.gripper, 'angle_1',...
                app.ZangeLinks_EditField, 'Value',...
                app.ZangeLinksGauge, 'Value'));
            iso_bm.addBinding(... %Winkel Zange Rechts
                Binding.PropertyBinding(...
                app.process.isoDevice.robot.gripper, 'angle_2',...
                app.ZangeRechts_EditField, 'Value',...
                app.ZangeRechtsGauge, 'Value'));
            iso_bm.addBinding(... %Zangenkontakt
                Binding.TriggerLampBinding(...
                app.process.isoDevice.robot.gripper,'has_contact',...
                app.KontaktLamp));
            iso_bm.addBinding(... %Unterdruck
                Binding.TriggerLampBinding(...
                app.process.isoDevice.robot,'vacuum_active',...
                app.VacuumSignalLamp));
            iso_bm.addBinding(... %Förderband Isolierung
                Binding.TriggerLampBinding(...
                app.process.isoDevice.convBelt,'is_active',...
                app.IsoForderbandAktiv_Lamp));
            iso_bm.addBinding(... %Lichtschranke Isolierung
                Binding.TriggerLampBinding(...
                app.process.isoDevice,'light_barrier_blocked',...
                app.IsoLichtschrankeLamp));
            iso_bm.addBinding(... %Trommelspannung
                Binding.PropertyBinding(...
                app.process.isoDevice.drumFeeder, 'drum_voltage',...
                app.DrumFeederSpannungEditField, 'Value'));
            iso_bm.addBinding(... %Trommelaktivität
                Binding.TriggerLampBinding(...
                app.process.isoDevice.drumFeeder,'is_active',...
                app.TrommelAktive_Lamp));
                        
%             robot_gripper_bm.timer.start()
end

