function addIsoDeviceGuiBindings(app,binding_logger)
%% ROBOT GRIPPER TAB
            iso_bm = Binding.BindingManager('IsoDevice',binding_logger);
            app.binding_managers.gripper = iso_bm;
%             app.RoboterGreiferTab.binding_managers = [app.RoboterGreiferTab.binding_managers, robot_gripper_bm];
%             robot_gripper_bm.timer_target_period = 0.1;

            iso_bm.addBinding(... %Winkel Zange Links
                Binding.PropertyBinding(...
                app.process.isoDevice.robot.gripper, 'angle_1',...
                app.ZangeLinks_EditField, 'Value',...
                app.ZangeLinksGauge, 'Value'));
            iso_bm.addBinding(... %Winkel Zange Rechts
                Binding.PropertyBinding(...
                app.process.isoDevice.robot.gripper, 'angle_2',...
                app.ZangeRechts_EditField, 'Value',...
                app.ZangeRechtsGauge, 'Value'));
            iso_bm.addBinding(... %Zangenkontakt
                Binding.TriggerLampBinding(...
                app.process.isoDevice.robot.gripper,'has_contact',...
                app.KontaktLamp));
            iso_bm.addBinding(... %Unterdruck
                Binding.TriggerLampBinding(...
                app.process.isoDevice.convBelt,'light_barrier_active',...
                app.VacuumSignalLamp));
            iso_bm.addBinding(... %Förderband Isolierung
                Binding.TriggerLampBinding(...
                app.process.isoDevice.convBelt,'is_active',...
                app.IsoForderbandAktiv_Lamp));
            iso_bm.addBinding(... %Lichtschranke Isolierung
                Binding.TriggerLampBinding(...
                app.process.isoDevice.convBelt,'light_barrier_active',...
                app.IsoLichtschrankeLamp));
            iso_bm.addBinding(... %Trommelspannung
                Binding.PropertyBinding(...
                app.process.isoDevice.drumFeeder, 'drum_voltage',...
                app.DrumFeederSpannungEditField, 'Value'));
            iso_bm.addBinding(... %Trommelaktivität
                Binding.TriggerLampBinding(...
                app.process.isoDevice.drumFeeder,'is_active',...
                app.TrommelAktive_Lamp));
            
            iso_bm.addBinding(... %Robot X
                Binding.PropertyBinding(...
                app.process.isoDevice.robot, 'x',...
                app.xEditField_2, 'Value'));
            
            iso_bm.addBinding(... %Robot Y
                Binding.PropertyBinding(...
                app.process.isoDevice.robot, 'y',...
                app.yEditField_2, 'Value'));
            
            iso_bm.addBinding(... %Robot Z
                Binding.PropertyBinding(...
                app.process.isoDevice.robot, 'z',...
                app.zEditField_2, 'Value'));
            
            iso_bm.addBinding(... %Robot RX
                Binding.PropertyBinding(...
                app.process.isoDevice.robot, 'rx',...
                app.rxEditField_2, 'Value'));
            
            iso_bm.addBinding(... %Robot RY
                Binding.PropertyBinding(...
                app.process.isoDevice.robot, 'y',...
                app.ryEditField_2, 'Value'));
            
            iso_bm.addBinding(... %Robot RZ
                Binding.PropertyBinding(...
                app.process.isoDevice.robot, 'rz',...
                app.rzEditField_2, 'Value'));
            
%             robot_gripper_bm.timer.start()
end

