function addProcessGuiBindings(app)
%% STATELAMP
            state_lamp_bm = GuiBinding.BindingManager();
            app.binding_managers.state_lamps = state_lamp_bm;

            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                app.process, app.Process_Lamp, app.Process_EditField));
            % ISOLATION DEVICE
            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                    app.process.isoDevice,...
                    app.IsolationDevice_Lamp, app.IsolationDevice_EditField));
            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                app.process.isoDevice.robot, app.Robot_Lamp, app.Robot_EditField));
            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                app.process.isoDevice.robot.objDetection, app.ObjectDetection_Lamp, app.ObjectDetection_EditField));
            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                app.process.isoDevice.robot.gripper, app.Gripper_Lamp, app.Gripper_EditField));
            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                app.process.isoDevice.drumFeeder, app.DrumFeeder_Lamp, app.DrumFeeder_EditField));
            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                app.process.isoDevice.convBelt, app.ConvBelt_Lamp, app.ConvBelt_EditField));
            % MEASURING SYSTEM
            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                app.process.measSystem, app.MeasuringSystem_Lamp, app.MeasuringSystem_EditField));
            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                app.process.measSystem.weighingBelt, app.WeighingBelt_Lamp, app.WeighingBelt_EditField));
            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                app.process.measSystem.cam, app.Camera_Lamp, app.Camera_EditField));
            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                app.process.measSystem.light, app.Light_Lamp, app.Light_EditField));
            state_lamp_bm.addBinding(...
                GuiBinding.StateLampBinding(...
                app.process.measSystem.scale, app.Scale_Lamp, app.Scale_EditField));
            
            state_lamp_bm.timer.start();
%% ROBOT GRIPPER TAB
            robot_gripper_bm = GuiBinding.BindingManager();
            app.binding_managers.gripper = robot_gripper_bm;
%             app.RoboterGreiferTab.binding_managers = [app.RoboterGreiferTab.binding_managers, robot_gripper_bm];
            robot_gripper_bm.timer_target_period = 0.1;

            robot_gripper_bm.addBinding(... %Winkel Zange Links
                GuiBinding.Fcn2PropertyBinding(...
                @(~,~)app.process.isoDevice.robot.gripper.readAngle1,...
                app.ZangeLinks_EditField, 'Value',...
                app.ZangeLinksGauge, 'Value'));
            robot_gripper_bm.addBinding(... %Winkel Zange Rechts
                GuiBinding.Fcn2PropertyBinding(...
                @(~,~)app.process.isoDevice.robot.gripper.readAngle2,...
                app.ZangeRechts_EditField, 'Value',...
                app.ZangeRechtsGauge, 'Value'));
            robot_gripper_bm.addBinding(... %Zangenkontakt
                GuiBinding.TriggerLampBinding(...
                @(~,~)app.process.isoDevice.robot.gripper.checkContact,...
                app.KontaktLamp));
            robot_gripper_bm.addBinding(... %Unterdruck
                GuiBinding.TriggerLampBinding(...
                @(~,~)app.process.isoDevice.convBelt.lightBarrierActivated,...
                app.VacuumSignalLamp));
            robot_gripper_bm.addBinding(... %Lichtschranke Isolierung
                GuiBinding.TriggerLampBinding(...
                @(~,~)app.process.isoDevice.convBelt.lightBarrierActivated,...
                app.IsoLichtschrankeLamp));
            
            robot_gripper_bm.timer.start()
end

