function addProcessGuiBindings(app)
            binding_logger = Logger.Logger();
            binding_logger.log_file_active = true;
            binding_logger.log_file_level = 1;
            binding_logger.log_file_path = 'bindings.log';
            binding_logger.log_print_active = false;
%             binding_logger.log_remote_fcn_handle = @app.logToTable;
%             binding_logger.log_remote_fcn_active = true;
%             binding_logger.log_remote_fcn_level = 1;
            
%% STATELAMP
            state_lamp_bm = Binding.BindingManager('State_Lamps',binding_logger);
            app.binding_managers.state_lamps = state_lamp_bm;
%             state_lamp_bm.timer_target_period = 1;

            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                app.process, app.Process_Lamp, app.Process_EditField));
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...g
                app.process.cANbus, app.Can_Lamp, app.Can_EditField));
            % ISOLATION DEVICE
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                    app.process.isoDevice,...
                    app.IsolationDevice_Lamp, app.IsolationDevice_EditField));
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                app.process.isoDevice.robot, app.Robot_Lamp, app.Robot_EditField));
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                app.process.isoDevice.robot.objDetection, app.ObjectDetection_Lamp, app.ObjectDetection_EditField));
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                app.process.isoDevice.robot.gripper, app.Gripper_Lamp, app.Gripper_EditField));
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                app.process.isoDevice.drumFeeder, app.DrumFeeder_Lamp, app.DrumFeeder_EditField));
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                app.process.isoDevice.convBelt, app.ConvBelt_Lamp, app.ConvBelt_EditField));
            % MEASURING SYSTEM
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                app.process.measSystem, app.MeasuringSystem_Lamp, app.MeasuringSystem_EditField));
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                app.process.measSystem.weighingBelt, app.WeighingBelt_Lamp, app.WeighingBelt_EditField));
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                app.process.measSystem.cam, app.Camera_Lamp, app.Camera_EditField));
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                app.process.measSystem.light, app.Light_Lamp, app.Light_EditField));
            state_lamp_bm.addBinding(...
                Binding.StateLampBinding(...
                app.process.measSystem.scale, app.Scale_Lamp, app.Scale_EditField));
            
            state_lamp_bm.addBinding(...
                Binding.PropertyBinding(...
                app.process, 'remaining_iterations', app.RemainingSamples_EditField, 'Value'));
            
%             state_lamp_bm.timer.start();

        addIsoDeviceGuiBindings(app,binding_logger);
        addMeasSystemGuiBindings(app,binding_logger);
end

